// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8WQ8-Y52pWKb-yj-T3zAL_9uFL_k8ENc',
    appId: '1:149640752709:web:6079b8584373f1c8c8bd2c',
    messagingSenderId: '149640752709',
    projectId: 'flutter-app-2aa0f',
    authDomain: 'flutter-app-2aa0f.firebaseapp.com',
    storageBucket: 'flutter-app-2aa0f.firebasestorage.app',
    measurementId: 'G-P8VCK44X86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR1LVqNrIj-PgM36pBqCg3toLLIoty9Vc',
    appId: '1:149640752709:android:b23861659518b59ec8bd2c',
    messagingSenderId: '149640752709',
    projectId: 'flutter-app-2aa0f',
    storageBucket: 'flutter-app-2aa0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfZHnWeTKzj9H9ensAvlsapQ263VNqIfU',
    appId: '1:149640752709:ios:c2a63316bab8d219c8bd2c',
    messagingSenderId: '149640752709',
    projectId: 'flutter-app-2aa0f',
    storageBucket: 'flutter-app-2aa0f.firebasestorage.app',
    iosBundleId: 'com.example.controllapp',
  );
}
